jenkins:
    password: 11dc5bf784c1a2554cf1a0b4160b92471a
    url: http://localhost:8082
    user: admin
kubernetes:
    path: upload/config
mysql:
    dbname: cshiaa
    dirver: mysql
    host: 1.15.70.113
    password: cshiaa
    port: "3306"
    username: cshiaa
storage:
    local:
        filepath: upload
    type: local
zap:
    filename: ./log/cshiaa.log
    level: Info
    maxage: 30
    maxbackups: 3
    maxsize: 10
